name: boostsecurity.io (Dev)
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  boost-sbom:
    name: SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SBOM
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_TOKEN_DEV }}
          registry_module: boostsecurityio/trivy-sbom
