name: SAST
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'INFO' 
        type: choice
        options:
        - INFO
        - DEBUG
  push:
    branches:
      - master
jobs:
  boost_security_sast:
    name: Boost Security / Native Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v3
        env:
          BOOST_LOG_LEVEL: ${{ github.event.inputs.logLevel }}
        with:
          action: scan
          api_token: ${{ secrets.BOOST_API_KEY }}